name: CI
on:
    push:
        branches:
            - "**"
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: npm/actions-setup@v4
              with:
                version: 7
            - uses: actions/setup-node@v3
              with:
                node-version: 18.x
                registry-url: 'https://registry.npmjs.org'

            - run: npm install --frozen-lockfile
            - run: npm run ci